from invoke.parser import ParserContext
from invoke.runners import Result
from invoke.util import ExceptionWrapper

# ruff: noqa: N818

class CollectionNotFound(Exception):
    def __init__(self, name: str, start: str) -> None: ...

class Failure(Exception):
    def __init__(
        self, result: Result, reason: WatcherError | None = ...
    ) -> None: ...
    def streams_for_display(self) -> tuple[str, str]: ...

class UnexpectedExit(Failure): ...

class CommandTimedOut(Failure):
    def __init__(self, result: Result, timeout: int) -> None: ...

class AuthFailure(Failure):
    def __init__(self, result: Result, prompt: str) -> None: ...

class ParseError(Exception):
    def __init__(
        self, msg: str, context: ParserContext | None = ...
    ) -> None: ...

class Exit(Exception):
    def __init__(
        self, message: str | None = ..., code: int | None = ...
    ) -> None: ...
    @property
    def code(self) -> int: ...

class PlatformError(Exception): ...
class AmbiguousEnvVar(Exception): ...
class UncastableEnvVar(Exception): ...
class UnknownFileType(Exception): ...
class UnpicklableConfigMember(Exception): ...

class ThreadException(Exception):
    exceptions: tuple[ExceptionWrapper, ...] = ...
    def __init__(self, exceptions: list[ExceptionWrapper]) -> None: ...

class WatcherError(Exception): ...
class ResponseNotAccepted(WatcherError): ...
class SubprocessPipeError(Exception): ...
