from collections.abc import Generator
from contextlib import contextmanager
from typing import IO

def pty_size() -> tuple[int, int]: ...
def stdin_is_foregrounded_tty(stream: IO[str]) -> bool: ...
def cbreak_already_set(stream: IO[str]) -> bool: ...
@contextmanager
def character_buffered(stream: IO[str]) -> Generator[None]: ...
def ready_for_reading(input_: IO[str]) -> bool: ...
def bytes_to_read(input_: IO[str]) -> int: ...
