import threading
from collections.abc import Generator
from contextlib import contextmanager
from typing import IO, Any, NamedTuple

LOG_FORMAT = ...

def enable_logging() -> None: ...

log = ...
debug = ...

def task_name_sort_key(name: str) -> tuple[list[str], str]: ...
@contextmanager
def cd(where: str) -> Generator[None]: ...
def has_fileno(stream: IO[str]) -> bool: ...
def isatty(stream: IO[str]) -> bool | Any: ...  # noqa: ANN401
def helpline(obj: object) -> str | None: ...

class ExceptionHandlingThread(threading.Thread):
    def __init__(self, **kwargs: Any) -> None: ...  # noqa: ANN401
    def run(self) -> None: ...
    def exception(self) -> ExceptionWrapper | None: ...
    @property
    def is_dead(self) -> bool: ...

class ExceptionWrapper(NamedTuple):
    kwargs: Any
    type: Any
    value: Any
    traceback: Any
