import threading
from collections.abc import Generator, Iterable

class StreamWatcher(threading.local):
    def submit(self, stream: str) -> Iterable[str]: ...

class Responder(StreamWatcher):
    def __init__(self, pattern: str, response: str) -> None: ...
    def pattern_matches(
        self, stream: str, pattern: str, index_attr: str
    ) -> Iterable[str]: ...
    def submit(self, stream: str) -> Generator[str]: ...

class FailingResponder(Responder):
    def __init__(self, pattern: str, response: str, sentinel: str) -> None: ...
    def submit(self, stream: str) -> Generator[str]: ...
