from collections.abc import Iterable
from typing import Any

from invoke.parser.argument import Argument

def translate_underscores(name: str) -> str: ...
def to_flag(name: str) -> str: ...
def sort_candidate(arg: Argument) -> str: ...
def flag_key(arg: Argument) -> list[int | str]: ...

class ParserContext:
    def __init__(
        self,
        name: str | None = ...,
        aliases: Iterable[str] = ...,
        args: Iterable[Argument] = ...,
    ) -> None: ...
    def add_arg(self, *args: Any, **kwargs: Any) -> None: ...  # noqa: ANN401
    @property
    def missing_positional_args(self) -> list[Argument]: ...
    @property
    def as_kwargs(self) -> dict[str, Any]: ...
    def names_for(self, flag: str) -> list[str]: ...
    def help_for(self, flag: str) -> tuple[str, str]: ...
    def help_tuples(self) -> list[tuple[str, str | None]]: ...
    def flag_names(self) -> tuple[str, ...]: ...
